name: trading
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - click
  - holidays
  - ipython
  - keras
  - matplotlib
  - numpy
  - pandas
  - pyyaml
  - requests
  - scikit-learn
  - setuptools
  - tensorflow
  - yaml
  - yfinance
